[[SoapyPlutoSDR]]
arch = "aarch64"
git-tree-sha1 = "33d766ad80259476f57fa9a3a386f70f91e8f982"
os = "macos"

    [[SoapyPlutoSDR.download]]
    sha256 = "c49825a069299a91690dd96a7ecef424f0562b47945dc9d04d205ed140193d77"
    url = "https://github.com/JuliaBinaryWrappers/SoapyPlutoSDR_jll.jl/releases/download/SoapyPlutoSDR-v0.2.1+0/SoapyPlutoSDR.v0.2.1.aarch64-apple-darwin.tar.gz"
[[SoapyPlutoSDR]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ad76d036b9fe274f8e89fc07c7783289ffe4848b"
libc = "glibc"
os = "linux"

    [[SoapyPlutoSDR.download]]
    sha256 = "3e95fdb80fb4e7faa9b1d299cfaca12af1eb7314ffc622ef0439a716da09887c"
    url = "https://github.com/JuliaBinaryWrappers/SoapyPlutoSDR_jll.jl/releases/download/SoapyPlutoSDR-v0.2.1+0/SoapyPlutoSDR.v0.2.1.aarch64-linux-gnu-cxx03.tar.gz"
[[SoapyPlutoSDR]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "04bf207d02713a7d3e81c801b2def2f59c47a7d6"
libc = "glibc"
os = "linux"

    [[SoapyPlutoSDR.download]]
    sha256 = "5114fdab5550d5a339a8258ec6bee1277a79970136b27c8648e09b6021a0c4d7"
    url = "https://github.com/JuliaBinaryWrappers/SoapyPlutoSDR_jll.jl/releases/download/SoapyPlutoSDR-v0.2.1+0/SoapyPlutoSDR.v0.2.1.aarch64-linux-gnu-cxx11.tar.gz"
[[SoapyPlutoSDR]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "65f86065dee4eeef55491056fd336cf42bb6ebe2"
libc = "musl"
os = "linux"

    [[SoapyPlutoSDR.download]]
    sha256 = "582a50d312e1fd5e6485fd6dedc20f3083d3f17d561a5e71e1d46bf8e71f8929"
    url = "https://github.com/JuliaBinaryWrappers/SoapyPlutoSDR_jll.jl/releases/download/SoapyPlutoSDR-v0.2.1+0/SoapyPlutoSDR.v0.2.1.aarch64-linux-musl-cxx03.tar.gz"
[[SoapyPlutoSDR]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "62a924f683a38420ebffc021a938f57507ae65cb"
libc = "musl"
os = "linux"

    [[SoapyPlutoSDR.download]]
    sha256 = "6478ac8f2585d5d4abb4d554cf04c84fed4dd16ac34c0894cf1d24f78aba63ba"
    url = "https://github.com/JuliaBinaryWrappers/SoapyPlutoSDR_jll.jl/releases/download/SoapyPlutoSDR-v0.2.1+0/SoapyPlutoSDR.v0.2.1.aarch64-linux-musl-cxx11.tar.gz"
[[SoapyPlutoSDR]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "415899a4158cd382285a37e406e5ab6c59842407"
libc = "glibc"
os = "linux"

    [[SoapyPlutoSDR.download]]
    sha256 = "e36c01922d3258acd001faa898bcb7ddcfc52d5bdd0fcf9258efc2e6f7bada25"
    url = "https://github.com/JuliaBinaryWrappers/SoapyPlutoSDR_jll.jl/releases/download/SoapyPlutoSDR-v0.2.1+0/SoapyPlutoSDR.v0.2.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[SoapyPlutoSDR]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "abffe50f6f6f8c166695a5a3d5dd73823809cbd7"
libc = "glibc"
os = "linux"

    [[SoapyPlutoSDR.download]]
    sha256 = "2a05b04ca18aabc7489f39dcdf0810caa56921dad063a11a341fba21a70300e1"
    url = "https://github.com/JuliaBinaryWrappers/SoapyPlutoSDR_jll.jl/releases/download/SoapyPlutoSDR-v0.2.1+0/SoapyPlutoSDR.v0.2.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[SoapyPlutoSDR]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "45e9c28c095c12f6d8315fbb3cc3f6c86c5e8e05"
libc = "musl"
os = "linux"

    [[SoapyPlutoSDR.download]]
    sha256 = "fb556359c8ceed295c37bd1b84765d4f91365910bbf416bbbd7d85d9a8720992"
    url = "https://github.com/JuliaBinaryWrappers/SoapyPlutoSDR_jll.jl/releases/download/SoapyPlutoSDR-v0.2.1+0/SoapyPlutoSDR.v0.2.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[SoapyPlutoSDR]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9b4df2bda4443423f73802bffb713903bbce0e44"
libc = "musl"
os = "linux"

    [[SoapyPlutoSDR.download]]
    sha256 = "6fc5be7915ae8b7be5b20c5258aa8532f1169dfb5612a44d58b0c5d754b4592a"
    url = "https://github.com/JuliaBinaryWrappers/SoapyPlutoSDR_jll.jl/releases/download/SoapyPlutoSDR-v0.2.1+0/SoapyPlutoSDR.v0.2.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[SoapyPlutoSDR]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "72218a0fc818d31ec4de92f8d33799a2db6e9608"
libc = "glibc"
os = "linux"

    [[SoapyPlutoSDR.download]]
    sha256 = "bbbb50a59a1ec616f9ed18e5f9f8e63e34dcae074ac6ed985cfca20c00b22aea"
    url = "https://github.com/JuliaBinaryWrappers/SoapyPlutoSDR_jll.jl/releases/download/SoapyPlutoSDR-v0.2.1+0/SoapyPlutoSDR.v0.2.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[SoapyPlutoSDR]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "05573748f370c76826b75df75732bc51e77ff978"
libc = "glibc"
os = "linux"

    [[SoapyPlutoSDR.download]]
    sha256 = "889eb73ea8e17c3814797292d5057904d029bf3c7cf76290dfdf6febb0064f77"
    url = "https://github.com/JuliaBinaryWrappers/SoapyPlutoSDR_jll.jl/releases/download/SoapyPlutoSDR-v0.2.1+0/SoapyPlutoSDR.v0.2.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[SoapyPlutoSDR]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8b32ad1582196983b7df21650a64267a184b300a"
libc = "musl"
os = "linux"

    [[SoapyPlutoSDR.download]]
    sha256 = "b6a3333c396ca69c9ead14842fd2332277b29d99864760d297695d3a880fc07d"
    url = "https://github.com/JuliaBinaryWrappers/SoapyPlutoSDR_jll.jl/releases/download/SoapyPlutoSDR-v0.2.1+0/SoapyPlutoSDR.v0.2.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[SoapyPlutoSDR]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f3d353552b70aaac0db9c4fe53b79abc6f911e82"
libc = "musl"
os = "linux"

    [[SoapyPlutoSDR.download]]
    sha256 = "eeeff63cbc194fd3c381cdaaba8066655a22b454c2d1f62defbe8587e66e22fc"
    url = "https://github.com/JuliaBinaryWrappers/SoapyPlutoSDR_jll.jl/releases/download/SoapyPlutoSDR-v0.2.1+0/SoapyPlutoSDR.v0.2.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[SoapyPlutoSDR]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "557361c15c3329318c37a924f851b54c6bdaa853"
libc = "glibc"
os = "linux"

    [[SoapyPlutoSDR.download]]
    sha256 = "5fa4857e1690935a3df928e113e98d3816a8a8f93cd4309b724aea6b0f719bc1"
    url = "https://github.com/JuliaBinaryWrappers/SoapyPlutoSDR_jll.jl/releases/download/SoapyPlutoSDR-v0.2.1+0/SoapyPlutoSDR.v0.2.1.i686-linux-gnu-cxx03.tar.gz"
[[SoapyPlutoSDR]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "596ef7cb436faab809c030fa8c827ded8527e523"
libc = "glibc"
os = "linux"

    [[SoapyPlutoSDR.download]]
    sha256 = "8a16e86f76b6c6251e1fe698e12b4033c759ae55957d1dfd9f711b45a350e178"
    url = "https://github.com/JuliaBinaryWrappers/SoapyPlutoSDR_jll.jl/releases/download/SoapyPlutoSDR-v0.2.1+0/SoapyPlutoSDR.v0.2.1.i686-linux-gnu-cxx11.tar.gz"
[[SoapyPlutoSDR]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7e0aa162f087474478248026f561d7b4775cc3f1"
libc = "musl"
os = "linux"

    [[SoapyPlutoSDR.download]]
    sha256 = "f0670addb1b1b5b15a7e5caa56dcbbbddfeb05121c1d55f8c364e379ea89d64b"
    url = "https://github.com/JuliaBinaryWrappers/SoapyPlutoSDR_jll.jl/releases/download/SoapyPlutoSDR-v0.2.1+0/SoapyPlutoSDR.v0.2.1.i686-linux-musl-cxx03.tar.gz"
[[SoapyPlutoSDR]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2c15fc7ee143e5e238f6cab872535fe8a80fabce"
libc = "musl"
os = "linux"

    [[SoapyPlutoSDR.download]]
    sha256 = "a01e642119278289f73668e5f0eec216e62eee41d05ca189e7f901bfe069c195"
    url = "https://github.com/JuliaBinaryWrappers/SoapyPlutoSDR_jll.jl/releases/download/SoapyPlutoSDR-v0.2.1+0/SoapyPlutoSDR.v0.2.1.i686-linux-musl-cxx11.tar.gz"
[[SoapyPlutoSDR]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ea4b49903e49027982fa02e5c6a778e0a6f5192e"
os = "windows"

    [[SoapyPlutoSDR.download]]
    sha256 = "1fd216d37f1b5bf4f5f44e63894a532b82d5d1fa582c893814bc48a66460c292"
    url = "https://github.com/JuliaBinaryWrappers/SoapyPlutoSDR_jll.jl/releases/download/SoapyPlutoSDR-v0.2.1+0/SoapyPlutoSDR.v0.2.1.i686-w64-mingw32-cxx03.tar.gz"
[[SoapyPlutoSDR]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "199d399c94007091d2fb45e4e74fb17fa9b6dbd7"
os = "windows"

    [[SoapyPlutoSDR.download]]
    sha256 = "7f3200a7887e63999962a9a44b9892910500bd14a49bad3552519423ea7c07d1"
    url = "https://github.com/JuliaBinaryWrappers/SoapyPlutoSDR_jll.jl/releases/download/SoapyPlutoSDR-v0.2.1+0/SoapyPlutoSDR.v0.2.1.i686-w64-mingw32-cxx11.tar.gz"
[[SoapyPlutoSDR]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "92a3636633c44711d3cfbc778e215be4d9ddc856"
libc = "glibc"
os = "linux"

    [[SoapyPlutoSDR.download]]
    sha256 = "b798048ae4b0941f8f898fae21e67c36193321db21aeaa76a61a8880a6e04f40"
    url = "https://github.com/JuliaBinaryWrappers/SoapyPlutoSDR_jll.jl/releases/download/SoapyPlutoSDR-v0.2.1+0/SoapyPlutoSDR.v0.2.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[SoapyPlutoSDR]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0395c88a9bcbeb2c494c4cc581ecad858575ade5"
libc = "glibc"
os = "linux"

    [[SoapyPlutoSDR.download]]
    sha256 = "bd1e6daecfa5f762aeea40eb8ecb8f06bb7d19a00f2152640c950c3b1f01695e"
    url = "https://github.com/JuliaBinaryWrappers/SoapyPlutoSDR_jll.jl/releases/download/SoapyPlutoSDR-v0.2.1+0/SoapyPlutoSDR.v0.2.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[SoapyPlutoSDR]]
arch = "x86_64"
git-tree-sha1 = "b57cc6aad1a44790c54e5f400c0abdcabc22d23b"
os = "macos"

    [[SoapyPlutoSDR.download]]
    sha256 = "df2a116fd413275c2110beb2b52d0929e5ca97263c854c8f9168f3e26b810d31"
    url = "https://github.com/JuliaBinaryWrappers/SoapyPlutoSDR_jll.jl/releases/download/SoapyPlutoSDR-v0.2.1+0/SoapyPlutoSDR.v0.2.1.x86_64-apple-darwin.tar.gz"
[[SoapyPlutoSDR]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d46b6cfef643c977ab7937e1f9a026b97d571223"
libc = "glibc"
os = "linux"

    [[SoapyPlutoSDR.download]]
    sha256 = "92828efc4a8d97e7dcf4da5d04014a7dd57f1543982f426bdfb5422b8f110651"
    url = "https://github.com/JuliaBinaryWrappers/SoapyPlutoSDR_jll.jl/releases/download/SoapyPlutoSDR-v0.2.1+0/SoapyPlutoSDR.v0.2.1.x86_64-linux-gnu-cxx03.tar.gz"
[[SoapyPlutoSDR]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5836ffd27e05350108dd14fde70ede3a56815cd6"
libc = "glibc"
os = "linux"

    [[SoapyPlutoSDR.download]]
    sha256 = "4b4bc5eaf0a55a4b3ed1fda280e8c370443e56807f3415570cc6281da7fff1a9"
    url = "https://github.com/JuliaBinaryWrappers/SoapyPlutoSDR_jll.jl/releases/download/SoapyPlutoSDR-v0.2.1+0/SoapyPlutoSDR.v0.2.1.x86_64-linux-gnu-cxx11.tar.gz"
[[SoapyPlutoSDR]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "df1c130fac811368faa333974308669aad4ec82d"
libc = "musl"
os = "linux"

    [[SoapyPlutoSDR.download]]
    sha256 = "a60008e36e48559f47782aefa622c6ab26365867d21cbb81b89c9cefe52fe95b"
    url = "https://github.com/JuliaBinaryWrappers/SoapyPlutoSDR_jll.jl/releases/download/SoapyPlutoSDR-v0.2.1+0/SoapyPlutoSDR.v0.2.1.x86_64-linux-musl-cxx03.tar.gz"
[[SoapyPlutoSDR]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d98b2d7eb72fcb622b4786d537e774b36a0d36bc"
libc = "musl"
os = "linux"

    [[SoapyPlutoSDR.download]]
    sha256 = "a487285ba30039223f7bf8dc9eae317bce261d7140dc71f69f950cc02275d652"
    url = "https://github.com/JuliaBinaryWrappers/SoapyPlutoSDR_jll.jl/releases/download/SoapyPlutoSDR-v0.2.1+0/SoapyPlutoSDR.v0.2.1.x86_64-linux-musl-cxx11.tar.gz"
[[SoapyPlutoSDR]]
arch = "x86_64"
git-tree-sha1 = "3a2895991597d967e59a6c13968b61a679d1dd15"
os = "freebsd"

    [[SoapyPlutoSDR.download]]
    sha256 = "4472fb46a601b1b5dbeb3f3dacede0acf72d3457bd730112defc3c316d86ea7b"
    url = "https://github.com/JuliaBinaryWrappers/SoapyPlutoSDR_jll.jl/releases/download/SoapyPlutoSDR-v0.2.1+0/SoapyPlutoSDR.v0.2.1.x86_64-unknown-freebsd.tar.gz"
[[SoapyPlutoSDR]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2678cb81b217becb8e8a858262445aa46b081870"
os = "windows"

    [[SoapyPlutoSDR.download]]
    sha256 = "63602013e11b4535285094a07c522405f068ac58fd6b5d0fe23cbe7a37db5d7c"
    url = "https://github.com/JuliaBinaryWrappers/SoapyPlutoSDR_jll.jl/releases/download/SoapyPlutoSDR-v0.2.1+0/SoapyPlutoSDR.v0.2.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[SoapyPlutoSDR]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ededd967c40fa54c0413f100d5334e5714891e5b"
os = "windows"

    [[SoapyPlutoSDR.download]]
    sha256 = "5165df27816c92e446729429307803eff88ffe12eab21fc9a7ca48d6d06938ab"
    url = "https://github.com/JuliaBinaryWrappers/SoapyPlutoSDR_jll.jl/releases/download/SoapyPlutoSDR-v0.2.1+0/SoapyPlutoSDR.v0.2.1.x86_64-w64-mingw32-cxx11.tar.gz"
