[[SoapyPlutoSDR]]
arch = "aarch64"
git-tree-sha1 = "2038f506726b93c13401bc1dc18dedbe46593022"
os = "macos"

    [[SoapyPlutoSDR.download]]
    sha256 = "7b58a786518547bcaa057170298ac8f968722facc0ba4b5759632342cb21dfdd"
    url = "https://github.com/JuliaBinaryWrappers/SoapyPlutoSDR_jll.jl/releases/download/SoapyPlutoSDR-v0.2.1+1/SoapyPlutoSDR.v0.2.1.aarch64-apple-darwin.tar.gz"
[[SoapyPlutoSDR]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "15e66407917f22c28970b1024b1c50747a9ba739"
libc = "glibc"
os = "linux"

    [[SoapyPlutoSDR.download]]
    sha256 = "3adbe75298c0e5a9c03ddbf3ef2bd0a385f357a33157d5ea4492856c75a0fed3"
    url = "https://github.com/JuliaBinaryWrappers/SoapyPlutoSDR_jll.jl/releases/download/SoapyPlutoSDR-v0.2.1+1/SoapyPlutoSDR.v0.2.1.aarch64-linux-gnu-cxx03.tar.gz"
[[SoapyPlutoSDR]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a7f488215301ff0163a7be077442eaafd3e2c0eb"
libc = "glibc"
os = "linux"

    [[SoapyPlutoSDR.download]]
    sha256 = "fa486a409440950b650c0017329121407c4c51a75d0a60f5f1c5d81079b6f6d3"
    url = "https://github.com/JuliaBinaryWrappers/SoapyPlutoSDR_jll.jl/releases/download/SoapyPlutoSDR-v0.2.1+1/SoapyPlutoSDR.v0.2.1.aarch64-linux-gnu-cxx11.tar.gz"
[[SoapyPlutoSDR]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "596f247e884d4fa40b37f7e4ca707c3c82e2fe31"
libc = "musl"
os = "linux"

    [[SoapyPlutoSDR.download]]
    sha256 = "c0fc3936bf77f06073722b9867ec2462f14bdea7da283cc357b1493b7e268dd9"
    url = "https://github.com/JuliaBinaryWrappers/SoapyPlutoSDR_jll.jl/releases/download/SoapyPlutoSDR-v0.2.1+1/SoapyPlutoSDR.v0.2.1.aarch64-linux-musl-cxx03.tar.gz"
[[SoapyPlutoSDR]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4ef4520cbc48ebedde8160e0b0336a79f8f1a337"
libc = "musl"
os = "linux"

    [[SoapyPlutoSDR.download]]
    sha256 = "d5e56c47414c3fbe58ee2942cd8454da92210f32faabc1b418ff5c7bd14db732"
    url = "https://github.com/JuliaBinaryWrappers/SoapyPlutoSDR_jll.jl/releases/download/SoapyPlutoSDR-v0.2.1+1/SoapyPlutoSDR.v0.2.1.aarch64-linux-musl-cxx11.tar.gz"
[[SoapyPlutoSDR]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ac8597cdb817ee2d0cd26093cb6caefa5d3bcefa"
libc = "glibc"
os = "linux"

    [[SoapyPlutoSDR.download]]
    sha256 = "5f22c6c98c713d9a6ebb58f3a00cf3924f71c77afd547daeea7d083f73316471"
    url = "https://github.com/JuliaBinaryWrappers/SoapyPlutoSDR_jll.jl/releases/download/SoapyPlutoSDR-v0.2.1+1/SoapyPlutoSDR.v0.2.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[SoapyPlutoSDR]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bc27969e4cc4da565372c86c5fd241d2f764def2"
libc = "glibc"
os = "linux"

    [[SoapyPlutoSDR.download]]
    sha256 = "bcf89d0589ca619126d14a290265587fdb5c03c74a48d84091c272b27d753023"
    url = "https://github.com/JuliaBinaryWrappers/SoapyPlutoSDR_jll.jl/releases/download/SoapyPlutoSDR-v0.2.1+1/SoapyPlutoSDR.v0.2.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[SoapyPlutoSDR]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "605bef694ab2c5f0b40b1a9b1ae53638759dd8a3"
libc = "musl"
os = "linux"

    [[SoapyPlutoSDR.download]]
    sha256 = "a6633dfe6ebddda1d1c2911e7525e0bf22b5304cdf68378192dc07f123df6890"
    url = "https://github.com/JuliaBinaryWrappers/SoapyPlutoSDR_jll.jl/releases/download/SoapyPlutoSDR-v0.2.1+1/SoapyPlutoSDR.v0.2.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[SoapyPlutoSDR]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a4f669e136096fd3249ecdf6c80b6e0125a181cc"
libc = "musl"
os = "linux"

    [[SoapyPlutoSDR.download]]
    sha256 = "102e70b1a2fc59307d602ed4fccf036f6ff65ca9c14179ba8f0476561161f6fc"
    url = "https://github.com/JuliaBinaryWrappers/SoapyPlutoSDR_jll.jl/releases/download/SoapyPlutoSDR-v0.2.1+1/SoapyPlutoSDR.v0.2.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[SoapyPlutoSDR]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2bd93cdf9f8d8957defa3c8dbb78834144b57a2d"
libc = "glibc"
os = "linux"

    [[SoapyPlutoSDR.download]]
    sha256 = "b367bfb47344edac16729924c6486b684b7fabe1ae3a85f1feacd7f0a8fd9e87"
    url = "https://github.com/JuliaBinaryWrappers/SoapyPlutoSDR_jll.jl/releases/download/SoapyPlutoSDR-v0.2.1+1/SoapyPlutoSDR.v0.2.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[SoapyPlutoSDR]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4592c4be00ac109592c727ad9d185bf26077f8cf"
libc = "glibc"
os = "linux"

    [[SoapyPlutoSDR.download]]
    sha256 = "bc87f3f00c49d0b5611a02badd875689272350676ab4561414b4275a4c1699b3"
    url = "https://github.com/JuliaBinaryWrappers/SoapyPlutoSDR_jll.jl/releases/download/SoapyPlutoSDR-v0.2.1+1/SoapyPlutoSDR.v0.2.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[SoapyPlutoSDR]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1e5d5bd3e7fd907b79be71f86ce83eb4380f4c9c"
libc = "musl"
os = "linux"

    [[SoapyPlutoSDR.download]]
    sha256 = "423f143b5226bf75e79e68d54e11d8bc9612b9c57c79929674994a8c0909f188"
    url = "https://github.com/JuliaBinaryWrappers/SoapyPlutoSDR_jll.jl/releases/download/SoapyPlutoSDR-v0.2.1+1/SoapyPlutoSDR.v0.2.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[SoapyPlutoSDR]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f427bef9798ff3cf3e047e978be16982e7121a7b"
libc = "musl"
os = "linux"

    [[SoapyPlutoSDR.download]]
    sha256 = "90948d23c66c23ac2ffe1c44a17f4ad342ac28558efaef1c4f315b9eb9bfb710"
    url = "https://github.com/JuliaBinaryWrappers/SoapyPlutoSDR_jll.jl/releases/download/SoapyPlutoSDR-v0.2.1+1/SoapyPlutoSDR.v0.2.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[SoapyPlutoSDR]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a67be9f91ce42144e37eb9fcd7e7921dddd71e43"
libc = "glibc"
os = "linux"

    [[SoapyPlutoSDR.download]]
    sha256 = "79c04a61e81361dd3dd2850e300f75b568e2e530feed00bd5438afb0341f0dfc"
    url = "https://github.com/JuliaBinaryWrappers/SoapyPlutoSDR_jll.jl/releases/download/SoapyPlutoSDR-v0.2.1+1/SoapyPlutoSDR.v0.2.1.i686-linux-gnu-cxx03.tar.gz"
[[SoapyPlutoSDR]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8b1adf6957ce48c13d8bdf51ccffb367147db215"
libc = "glibc"
os = "linux"

    [[SoapyPlutoSDR.download]]
    sha256 = "7f408aac36b995091eba3fa1066f4a013348ca797b6fbb07ab9dc0542d053fad"
    url = "https://github.com/JuliaBinaryWrappers/SoapyPlutoSDR_jll.jl/releases/download/SoapyPlutoSDR-v0.2.1+1/SoapyPlutoSDR.v0.2.1.i686-linux-gnu-cxx11.tar.gz"
[[SoapyPlutoSDR]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4bd50a39add69c9ddbe6e9dd17af5a8e98399079"
libc = "musl"
os = "linux"

    [[SoapyPlutoSDR.download]]
    sha256 = "eb7c86b7afb49f7219750fed23981bc1742f3b6ce94bd68321fd10e9e06a774e"
    url = "https://github.com/JuliaBinaryWrappers/SoapyPlutoSDR_jll.jl/releases/download/SoapyPlutoSDR-v0.2.1+1/SoapyPlutoSDR.v0.2.1.i686-linux-musl-cxx03.tar.gz"
[[SoapyPlutoSDR]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c524d8e6e3916b806f4d6ea7e92ce8bcc5f087e5"
libc = "musl"
os = "linux"

    [[SoapyPlutoSDR.download]]
    sha256 = "1f6e413fdbcada388071ab8c583b6a5419a182defe0a2d8aa58660ee0be5d46a"
    url = "https://github.com/JuliaBinaryWrappers/SoapyPlutoSDR_jll.jl/releases/download/SoapyPlutoSDR-v0.2.1+1/SoapyPlutoSDR.v0.2.1.i686-linux-musl-cxx11.tar.gz"
[[SoapyPlutoSDR]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "435a8c221cd0042444609655eba679d168975aaa"
os = "windows"

    [[SoapyPlutoSDR.download]]
    sha256 = "157a14ba04c815c3365333da278a5e82e964a102bb44ee26994874a90754e25d"
    url = "https://github.com/JuliaBinaryWrappers/SoapyPlutoSDR_jll.jl/releases/download/SoapyPlutoSDR-v0.2.1+1/SoapyPlutoSDR.v0.2.1.i686-w64-mingw32-cxx03.tar.gz"
[[SoapyPlutoSDR]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ab3cd0db931f74a62ebb148f52933cf4ab6897d1"
os = "windows"

    [[SoapyPlutoSDR.download]]
    sha256 = "b24b3203468decdfb9f77c192b915c728b5390a850303ca4a34df0d90322525a"
    url = "https://github.com/JuliaBinaryWrappers/SoapyPlutoSDR_jll.jl/releases/download/SoapyPlutoSDR-v0.2.1+1/SoapyPlutoSDR.v0.2.1.i686-w64-mingw32-cxx11.tar.gz"
[[SoapyPlutoSDR]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "18a06ee79914ab1f97003f77424bfd0b452c2723"
libc = "glibc"
os = "linux"

    [[SoapyPlutoSDR.download]]
    sha256 = "72ecb7dd7f28656b58389330604a9beffbd65378899b697c5d30e591961f7d39"
    url = "https://github.com/JuliaBinaryWrappers/SoapyPlutoSDR_jll.jl/releases/download/SoapyPlutoSDR-v0.2.1+1/SoapyPlutoSDR.v0.2.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[SoapyPlutoSDR]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "08047cd1b396a521e3264e7bce1284a8f959dc20"
libc = "glibc"
os = "linux"

    [[SoapyPlutoSDR.download]]
    sha256 = "16043a68e6f905b427f8b836c4146f6666bcba911071c9b223d483169e438d13"
    url = "https://github.com/JuliaBinaryWrappers/SoapyPlutoSDR_jll.jl/releases/download/SoapyPlutoSDR-v0.2.1+1/SoapyPlutoSDR.v0.2.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[SoapyPlutoSDR]]
arch = "x86_64"
git-tree-sha1 = "2962ccd978a4156b8b16dbbeaaa38fee19b7a49c"
os = "macos"

    [[SoapyPlutoSDR.download]]
    sha256 = "da9592d9462707eaae3fe1c97f0907be90e4dcb9082f71e7fe5ab670f0f66e72"
    url = "https://github.com/JuliaBinaryWrappers/SoapyPlutoSDR_jll.jl/releases/download/SoapyPlutoSDR-v0.2.1+1/SoapyPlutoSDR.v0.2.1.x86_64-apple-darwin.tar.gz"
[[SoapyPlutoSDR]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "72581ab2560d457681c05d54c36a9251b2719931"
libc = "glibc"
os = "linux"

    [[SoapyPlutoSDR.download]]
    sha256 = "257962987348a405835384126c16e2a75089ae20168851adb3f15f184ebcb64b"
    url = "https://github.com/JuliaBinaryWrappers/SoapyPlutoSDR_jll.jl/releases/download/SoapyPlutoSDR-v0.2.1+1/SoapyPlutoSDR.v0.2.1.x86_64-linux-gnu-cxx03.tar.gz"
[[SoapyPlutoSDR]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d2e6c28722ebdb6aa70e6f99b68a2b3adf4efa7f"
libc = "glibc"
os = "linux"

    [[SoapyPlutoSDR.download]]
    sha256 = "c6b06aa1fe0865010da1eddb0c1d9474f401be32500d903584e4376dad4c0d8e"
    url = "https://github.com/JuliaBinaryWrappers/SoapyPlutoSDR_jll.jl/releases/download/SoapyPlutoSDR-v0.2.1+1/SoapyPlutoSDR.v0.2.1.x86_64-linux-gnu-cxx11.tar.gz"
[[SoapyPlutoSDR]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "46af02088b5ba393c6323cbd5ac4ba5e0afbb68a"
libc = "musl"
os = "linux"

    [[SoapyPlutoSDR.download]]
    sha256 = "8a77ebf52dc6fcf8989a5b3db1853a2a0b3bdc19795e5c6e24ed9bebfc91780c"
    url = "https://github.com/JuliaBinaryWrappers/SoapyPlutoSDR_jll.jl/releases/download/SoapyPlutoSDR-v0.2.1+1/SoapyPlutoSDR.v0.2.1.x86_64-linux-musl-cxx03.tar.gz"
[[SoapyPlutoSDR]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1a5256958b001f915e8907af69564d26516262ac"
libc = "musl"
os = "linux"

    [[SoapyPlutoSDR.download]]
    sha256 = "c9fefe398ae2103c38ba03b2fa1795afd186302517690698e5975098b45ab79d"
    url = "https://github.com/JuliaBinaryWrappers/SoapyPlutoSDR_jll.jl/releases/download/SoapyPlutoSDR-v0.2.1+1/SoapyPlutoSDR.v0.2.1.x86_64-linux-musl-cxx11.tar.gz"
[[SoapyPlutoSDR]]
arch = "x86_64"
git-tree-sha1 = "435a9762c59e7c63d6f984732d0a78e89a81222a"
os = "freebsd"

    [[SoapyPlutoSDR.download]]
    sha256 = "78081096678b6d00f5fab70e1a37e54165f5b538fe5c1da83de5083434b8043f"
    url = "https://github.com/JuliaBinaryWrappers/SoapyPlutoSDR_jll.jl/releases/download/SoapyPlutoSDR-v0.2.1+1/SoapyPlutoSDR.v0.2.1.x86_64-unknown-freebsd.tar.gz"
[[SoapyPlutoSDR]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a7a3684c2dfd6e25d4c0d9d0b4a2070631552eb5"
os = "windows"

    [[SoapyPlutoSDR.download]]
    sha256 = "9af03093343900534d78224fc3ddfe45824e127c3735ed1d8990732168da4457"
    url = "https://github.com/JuliaBinaryWrappers/SoapyPlutoSDR_jll.jl/releases/download/SoapyPlutoSDR-v0.2.1+1/SoapyPlutoSDR.v0.2.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[SoapyPlutoSDR]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "70d0ec290c57b347758ca8c3d07673fb6e490931"
os = "windows"

    [[SoapyPlutoSDR.download]]
    sha256 = "c4587c40c156e303061a81cc2f3b0a254e24d30030f53684180719571cc49cfa"
    url = "https://github.com/JuliaBinaryWrappers/SoapyPlutoSDR_jll.jl/releases/download/SoapyPlutoSDR-v0.2.1+1/SoapyPlutoSDR.v0.2.1.x86_64-w64-mingw32-cxx11.tar.gz"
